version: "3.9"
services:

  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./frontend/public/:/var/www/html/:ro
    networks:
      - bp-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - bp-network

#   frontend:
#     container_name: frontend
#     build:
#       context: ./frontend
#     restart: always
#     env_file: .env
#     ports:
#       - "${FRONTEND_PORT}:${FRONTEND_PORT}"
#     volumes:
#       - "./frontend/src:/usr/src/app/src"
#     networks:
#       - bp-network
#     command: "npm start"
#   backend:
#     container_name: backend
#     build:
#       context: ./backend
#     restart: always
#     env_file: .env
#     volumes:
#       - ./backend:/svr/app
#       - /svr/app/node_modules
#     networks:
#       - bp-network
#     ports:
#       - "${BACKEND_PORT}:${BACKEND_PORT}"
#     depends_on:
#       - bp-pg-db
#     links:
#       - bp-pg-db
#   bp-pg-db:
#     image: postgres:16-alpine
#     restart: always
#     container_name: bp-pg-db
#     env_file:
#       - .env
#     environment:
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_DB: ${POSTGRES_DB}
#     ports:
#       - "${DB_PORT}:${DB_PORT}"
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     networks:
#       - bp-network
#   pgadmin-portal:
#     image: dpage/pgadmin4
#     restart: always
#     container_name: pgadmin-portal
#     env_file:
#       - .env
#     environment:
#       PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
#       PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
#     volumes:
#       - pgadmin:/root/.pgadmin
#     ports:
#       - "${PGADMIN_PORT}:80"
#     depends_on:
#       - bp-pg-db
#     networks:
#       - bp-network
# volumes:
#   pgdata:
#   pgadmin:
networks:
  bp-network:
    driver: bridge
